import { ThreatAlert } from '../types/threat'

export const mockThreats: ThreatAlert[] = [
  {
    id: 'AL-2041',
    alertCode: 'AL-2041',
    title: 'Possible Command & Control (C2) Activity via High-Entropy DNS & Encrypted Beaconing',
    deviceId: 'SERVER-99',
    deviceHostname: 'CORE-DB-CLUSTER-01',
    deviceIp: '10.0.2.99',
    threatCategory: 'Command & Control',
    severity: 'CRITICAL',
    confidenceScore: 94,
    compromiseProbability: 88,
    detectedAt: '2 min ago',
    status: 'INVESTIGATING',
    summary: 'SERVER-99 is generating periodic encrypted outbound heartbeat pulses (30.02s interval) with near-zero jitter to IP 185.220.101.5 alongside high Shannon entropy DGA DNS queries.',
    indicators: [
      { type: 'Domain', value: 'x9q7f-tunnel-c2.biz (Entropy 4.88)', reputation: 'Untrusted/Dynamic C2' },
      { type: 'IP', value: '185.220.101.5:443', reputation: 'Bulletproof ASN 49302' },
      { type: 'Jitter', value: '0.4% interval variance', reputation: 'Automated Bot Beacon' },
      { type: 'Entropy', value: '4.88 Shannon Score', reputation: 'Algorithmically Generated Domain' },
    ],
    aiExplanation: 'The observed device behavior exhibits an 88% probabilistic deviation from normal database server baselines. The combination of static interval beaconing and high-entropy DNS tunnel payloads matches Cobalt Strike / Sliver C2 profiles.',
    remediationSteps: [
      'Isolate SERVER-99 immediately via network 802.1X quarantine',
      'Block outbound destination IP 185.220.101.5 on perimeter firewall FIREWALL-01',
      'Sinkhole DNS resolution for *.tunnel-c2.biz on internal resolvers',
      'Trigger memory dump & process capture on CORE-DB-CLUSTER-01 for forensics',
    ],
    assignedAnalyst: 'Agent Alex Rivera (Lead Responder)',
  },
  {
    id: 'AL-2042',
    alertCode: 'AL-2042',
    title: 'Abnormal Outbound Data Transfer Burst (14.2 GB Exfiltration)',
    deviceId: 'SERVER-99',
    deviceHostname: 'CORE-DB-CLUSTER-01',
    deviceIp: '10.0.2.99',
    threatCategory: 'Data Exfiltration',
    severity: 'CRITICAL',
    confidenceScore: 91,
    compromiseProbability: 85,
    detectedAt: '6 min ago',
    status: 'INVESTIGATING',
    summary: 'Sudden high-throughput outbound TLS stream transmitting 14.2 GB to unclassified foreign IP, exceeding 30-day baseline by 2,400%.',
    indicators: [
      { type: 'IP', value: '185.220.101.6:8443', reputation: 'Untrusted VPS Host' },
      { type: 'Process', value: 'ldap-exporter -> dump_db.sh injection', reputation: 'Suspicious Memory Allocation' },
    ],
    aiExplanation: 'Server baseline outbound volume averages < 500 MB/day. 14.2 GB exfiltration over port 8443 represents an extreme statistical deviation (z-score: 8.4).',
    remediationSteps: [
      'Terminate active TLS session #conn-01',
      'Review exfiltrated data egress classification',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2043',
    alertCode: 'AL-2043',
    title: 'High DNS DGA Query Entropy & Domain Generation Tunneling',
    deviceId: 'LAPTOP-PRO-7',
    deviceHostname: 'EXEC-LAPTOP-ALPHA',
    deviceIp: '10.0.3.44',
    threatCategory: 'DGA Tunneling',
    severity: 'HIGH',
    confidenceScore: 89,
    compromiseProbability: 64,
    detectedAt: '8 min ago',
    status: 'NEW',
    summary: 'Executive laptop LAPTOP-PRO-7 initiated abnormal high-entropy DNS resolution requests to unregistered TLD .xyz.',
    indicators: [
      { type: 'Domain', value: 'k98z-alpha-exfil.xyz', reputation: 'Dynamic DGA TLD' },
      { type: 'Entropy', value: '5.12 Shannon Score', reputation: 'Malicious DGA Signature' },
    ],
    aiExplanation: 'Executive laptop HAS never historically queried .xyz TLD domains. Anomaly confidence score 89%.',
    remediationSteps: [
      'Isolate LAPTOP-PRO-7 via SOC 802.1X quarantine',
      'Revoke Kerberos session tickets for CISO user account',
    ],
    assignedAnalyst: 'Unassigned',
  },
  {
    id: 'AL-2038',
    alertCode: 'AL-2038',
    title: 'Off-Hours Administrative Authentication Spike',
    deviceId: 'DEVICE-101',
    deviceHostname: 'FIN-WORKSTATION-101',
    deviceIp: '10.0.1.101',
    threatCategory: 'Credential Access',
    severity: 'MEDIUM',
    confidenceScore: 78,
    compromiseProbability: 45,
    detectedAt: '15 min ago',
    status: 'INVESTIGATING',
    summary: 'Multiple Kerberos ticket requests for privileged accounts originating at off-shift hours following 14 failed NTLM attempts.',
    indicators: [
      { type: 'Process', value: 'lsass.exe memory read attempt', reputation: 'Mimikatz-like artifact' },
    ],
    aiExplanation: 'Authentication cadence deviates from user Sarah Connor normal shift profile.',
    remediationSteps: [
      'Force password reset on account sconnor_adm',
      'Audit Active Directory event log ID 4624/4625',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2031',
    alertCode: 'AL-2031',
    title: 'Unusual Internal Subnet Discovery Scan',
    deviceId: 'IOT-GATEWAY-04',
    deviceHostname: 'SMART-BUILDING-HUB',
    deviceIp: '10.0.4.15',
    threatCategory: 'Reconnaissance',
    severity: 'LOW',
    confidenceScore: 68,
    compromiseProbability: 18,
    detectedAt: '24 min ago',
    status: 'RESOLVED',
    summary: 'Subnet probe on ports 22, 80, 443, 8080. Verified as scheduled internal asset discovery scan.',
    indicators: [
      { type: 'Port', value: 'SYN scan ports 22-8080', reputation: 'Approved internal scan' },
    ],
    aiExplanation: 'Traffic volume corresponds with weekly Nmap asset discovery script from Facilities IoT team.',
    remediationSteps: [
      'Marked as benign authorized scan',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2045',
    alertCode: 'AL-2045',
    title: 'High-Volume Shadow Volume Erasure & Ransomware Preparation',
    deviceId: 'SERVER-99',
    deviceHostname: 'CORE-DB-CLUSTER-01',
    deviceIp: '10.0.2.99',
    threatCategory: 'Command & Control',
    severity: 'CRITICAL',
    confidenceScore: 96,
    compromiseProbability: 95,
    detectedAt: 'Just now',
    status: 'NEW',
    summary: 'vssadmin.exe delete shadows /all /quiet command execution detected alongside sudden batch file renaming with high Shannon entropy extension.',
    indicators: [
      { type: 'Process', value: 'vssadmin.exe delete shadows /all /quiet', reputation: 'Ransomware Destructive Inhibitor' },
      { type: 'Entropy', value: '7.94 Encryption Score', reputation: 'Cryptographic Ransomware Pattern' },
    ],
    aiExplanation: 'Behavior matches LockBit / BlackCat pre-encryption staging routines. Bayesian confidence score 96%.',
    remediationSteps: [
      'Execute emergency 802.1X host isolation on SERVER-99',
      'Revoke core DB service credentials and terminate remote IPC sessions',
      'Mount immutable offline backup snapshots',
    ],
    assignedAnalyst: 'Unassigned',
  },
  {
    id: 'AL-2046',
    alertCode: 'AL-2046',
    title: 'Kerberoasting Ticket Harvesting Attempt targeting Service Accounts',
    deviceId: 'DEVICE-101',
    deviceHostname: 'FIN-WORKSTATION-101',
    deviceIp: '10.0.1.101',
    threatCategory: 'Credential Access',
    severity: 'HIGH',
    confidenceScore: 84,
    compromiseProbability: 68,
    detectedAt: '31 min ago',
    status: 'INVESTIGATING',
    summary: 'Multiple RC4-HMAC TGS requests for service principal names (SPNs) from non-Domain Controller workstation.',
    indicators: [
      { type: 'Process', value: 'Rubeus.exe /kerberoast', reputation: 'Active Directory Exploitation' },
      { type: 'IP', value: '10.0.1.101 -> 10.0.0.1:88', reputation: 'Suspicious SPN Enumeration' },
    ],
    aiExplanation: 'Request pattern indicates TGS ticket scraping for offline hash cracking.',
    remediationSteps: [
      'Rotate service account passwords for krbtgt and DB service accounts',
      'Enforce AES-256 Kerberos encryption requirement',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2047',
    alertCode: 'AL-2047',
    title: 'Base64 Encoded PowerShell Remote Execution Payload',
    deviceId: 'LAPTOP-PRO-7',
    deviceHostname: 'EXEC-LAPTOP-ALPHA',
    deviceIp: '10.0.3.44',
    threatCategory: 'Lateral Movement',
    severity: 'MEDIUM',
    confidenceScore: 76,
    compromiseProbability: 52,
    detectedAt: '45 min ago',
    status: 'NEW',
    summary: 'powershell.exe executed with -e / -enc Base64 payload containing obfuscated IEX download cradles.',
    indicators: [
      { type: 'Process', value: 'powershell.exe -enc JABzAD0...', reputation: 'Obfuscated Command Execution' },
    ],
    aiExplanation: 'Encoded script attempts to fetch secondary stage DLL from remote CDN IP.',
    remediationSteps: [
      'Terminate process tree for pid 8402',
      'Enable Constrained Language Mode in PowerShell Group Policy',
    ],
    assignedAnalyst: 'Unassigned',
  },
  {
    id: 'AL-2048',
    alertCode: 'AL-2048',
    title: 'Active Directory NTDS.dit Secret Hash Extraction via Volume Shadow Copy',
    deviceId: 'DB-ANALYTICS-08',
    deviceHostname: 'WAREHOUSE-ANALYTICS-DB',
    deviceIp: '10.0.2.188',
    threatCategory: 'Credential Access',
    severity: 'CRITICAL',
    confidenceScore: 97,
    compromiseProbability: 92,
    detectedAt: '1 min ago',
    status: 'NEW',
    summary: 'ntdsutil.exe ac i ntds "ifm" "create full C:\\Windows\\Temp\\NTDS" q q executed to dump Active Directory domain database secrets.',
    indicators: [
      { type: 'Process', value: 'ntdsutil.exe ac i ntds create full', reputation: 'NTDS.dit Secret Database Dump' },
      { type: 'Process', value: 'C:\\Windows\\Temp\\NTDS\\ntds.dit', reputation: 'Active Directory Credential Dump' },
    ],
    aiExplanation: 'Unauthorized domain controller database extraction attempt detected with 97% confidence. Implements MITRE technique [T1003.003 OS Credential Dumping].',
    remediationSteps: [
      'Execute emergency 802.1X quarantine on DB-ANALYTICS-08',
      'Invalidate Domain Admin Kerberos Ticket Granting Tickets (krbtgt)',
      'Perform emergency Active Directory password reset sweep',
    ],
    assignedAnalyst: 'Agent Alex Rivera (Lead Responder)',
  },
  {
    id: 'AL-2049',
    alertCode: 'AL-2049',
    title: 'SSH Reverse Port Forwarding Tunneling to External VPS Egress',
    deviceId: 'CLOUD-K8S-01',
    deviceHostname: 'K8S-MICROSERVICES-CLUSTER',
    deviceIp: '10.0.5.88',
    threatCategory: 'Command & Control',
    severity: 'HIGH',
    confidenceScore: 88,
    compromiseProbability: 79,
    detectedAt: '12 min ago',
    status: 'INVESTIGATING',
    summary: 'Persistent SSH reverse tunnel established over TCP 2222 from Kubernetes worker pod to unverified foreign VPS 198.51.100.44.',
    indicators: [
      { type: 'IP', value: '198.51.100.44:2222', reputation: 'Suspicious Tunnel Endpoint' },
      { type: 'Domain', value: 'SSH-2.0-OpenSSH_8.9 (Reverse -R 9050:localhost:22)', reputation: 'Encrypted Reverse Proxy' },
    ],
    aiExplanation: 'Subnet baseline prohibits outbound SSH port forwarding from Kubernetes nodes. Implements MITRE technique [T1572 Protocol Tunneling].',
    remediationSteps: [
      'Terminate pod container instance k8s-ingress-prod-04',
      'Inject egress drop rule for IP 198.51.100.44 on perimeter firewall FIREWALL-01',
    ],
    assignedAnalyst: 'Unassigned',
  },
  {
    id: 'AL-2050',
    alertCode: 'AL-2050',
    title: 'Malicious DLL Side-Loading & Memory Process Injection',
    deviceId: 'DEVPANEL-WS-09',
    deviceHostname: 'DEV-STAGING-LAPTOP',
    deviceIp: '10.0.3.89',
    threatCategory: 'Command & Control',
    severity: 'HIGH',
    confidenceScore: 85,
    compromiseProbability: 71,
    detectedAt: '22 min ago',
    status: 'NEW',
    summary: 'Legitimate signed executable loaded untrusted DLL payload (version.dll) from AppData\\Local\\Temp, injecting thread into explorer.exe.',
    indicators: [
      { type: 'Process', value: 'explorer.exe (PID 4920) -> VirtualAllocEx (PAGE_EXECUTE_READWRITE)', reputation: 'Process Injection' },
      { type: 'Process', value: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', reputation: 'Untrusted DLL Payload' },
    ],
    aiExplanation: 'Behavior exhibits classic DLL Side-Loading pattern bypassing Windows Defender signatures. Implements MITRE technique [T1574.002 DLL Side-Loading].',
    remediationSteps: [
      'Isolate DEVPANEL-WS-09 via 802.1X host containment',
      'Capture volatile RAM dump for YARA signature extraction',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2051',
    alertCode: 'AL-2051',
    title: 'Unauthorized Cloud API Secret Token Enumeration & Exfiltration',
    deviceId: 'AI-GPU-CLUSTER-03',
    deviceHostname: 'DEEP-LEARNING-NODE-03',
    deviceIp: '10.0.6.77',
    threatCategory: 'Credential Access',
    severity: 'MEDIUM',
    confidenceScore: 78,
    compromiseProbability: 48,
    detectedAt: '52 min ago',
    status: 'RESOLVED',
    summary: 'High frequency requests to AWS Instance Metadata Service (169.254.169.254) extracting IAM role security credentials.',
    indicators: [
      { type: 'IP', value: '169.254.169.254/latest/meta-data/iam/security-credentials/', reputation: 'IMDSv1 Credential Scraping' },
    ],
    aiExplanation: 'Automated script attempted IMDSv1 token harvest. Mitigated by enforcing IMDSv2 token headers.',
    remediationSteps: [
      'Enforce IMDSv2 requirement on all GPU cluster nodes',
      'Revoke IAM role temp tokens for AI-Research-Role',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2052',
    alertCode: 'AL-2052',
    title: 'LSASS Memory Process Dumping via Comsvcs MiniDump Injection',
    deviceId: 'WORKSTATION-SOC-02',
    deviceHostname: 'SOC-MONITORING-WS-02',
    deviceIp: '10.0.1.102',
    threatCategory: 'Credential Access',
    severity: 'CRITICAL',
    confidenceScore: 95,
    compromiseProbability: 91,
    detectedAt: 'Just now',
    status: 'NEW',
    summary: 'rundll32.exe C:\\Windows\\System32\\comsvcs.dll MiniDump lsass.exe process handle created to extract plaintext memory credentials.',
    indicators: [
      { type: 'Process', value: 'rundll32.exe comsvcs.dll MiniDump (PID 6720)', reputation: 'LSASS Process Memory Dump' },
      { type: 'Process', value: 'lsass.exe memory read handle (0x1F0FFF)', reputation: 'Credential Scraping' },
    ],
    aiExplanation: 'Behavior matches Mimikatz sekurlsa::logonpasswords in-memory dump routine. Bayesian confidence score 95%. Implements MITRE technique [T1003.001 LSASS Memory].',
    remediationSteps: [
      'Isolate WORKSTATION-SOC-02 immediately via 802.1X quarantine',
      'Enable LSA Protection (RunAsPPL) via Registry GPO',
      'Force password reset for all cached Domain Credentials',
    ],
    assignedAnalyst: 'Unassigned',
  },
  {
    id: 'AL-2053',
    alertCode: 'AL-2053',
    title: 'Active Directory DCSync Replication Emulation (DSGetNCChanges)',
    deviceId: 'PAYROLL-DB-02',
    deviceHostname: 'PAYROLL-VAULT-DB',
    deviceIp: '10.0.2.140',
    threatCategory: 'Credential Access',
    severity: 'HIGH',
    confidenceScore: 89,
    compromiseProbability: 82,
    detectedAt: '18 min ago',
    status: 'INVESTIGATING',
    summary: 'DSGetNCChanges RPC call issued over MS-DRSR from non-Domain Controller server to extract Active Directory password hashes.',
    indicators: [
      { type: 'IP', value: '10.0.2.140 -> 10.0.0.1:135 (RPC MS-DRSR)', reputation: 'Unauthorized DCSync Hop' },
      { type: 'Domain', value: 'Directory-Replication-Service (DRS-RPC)', reputation: 'Active Directory Hash Pull' },
    ],
    aiExplanation: 'Member server PAYROLL-VAULT-DB is not an authorized Domain Controller. Implements MITRE technique [T1003.006 DCSync].',
    remediationSteps: [
      'Revoke Replicating Directory Changes permissions from non-DC accounts',
      'Isolate PAYROLL-DB-02 via 802.1X containment',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
  {
    id: 'AL-2054',
    alertCode: 'AL-2054',
    title: 'WMI Remote Process Execution & Lateral Movement Staging',
    deviceId: 'DEVICE-101',
    deviceHostname: 'FIN-WORKSTATION-101',
    deviceIp: '10.0.1.101',
    threatCategory: 'Lateral Movement',
    severity: 'HIGH',
    confidenceScore: 86,
    compromiseProbability: 74,
    detectedAt: '28 min ago',
    status: 'NEW',
    summary: 'wmiprvse.exe spawned cmd.exe executing remote administrative tasks on adjacent workstations over WMI WinRM port 135.',
    indicators: [
      { type: 'Process', value: 'wmiprvse.exe -> cmd.exe /c powershell -enc', reputation: 'Remote WMI Execution' },
    ],
    aiExplanation: 'Workstation FIN-WORKSTATION-101 has no administrative justification for launching remote WMI sessions to VLAN 10.0.1.0/24.',
    remediationSteps: [
      'Restrict WMI/DCOM remote access via Local Windows Firewall rules',
      'Audit Active Directory event ID 4624 (Logon Type 3)',
    ],
    assignedAnalyst: 'Unassigned',
  },
  {
    id: 'AL-2055',
    alertCode: 'AL-2055',
    title: 'Suspicious Windows Scheduled Task Persistence Creation',
    deviceId: 'LAPTOP-PRO-7',
    deviceHostname: 'EXEC-LAPTOP-ALPHA',
    deviceIp: '10.0.3.44',
    threatCategory: 'Lateral Movement',
    severity: 'MEDIUM',
    confidenceScore: 77,
    compromiseProbability: 55,
    detectedAt: '40 min ago',
    status: 'RESOLVED',
    summary: 'schtasks.exe /create /tn "WindowsUpdateTask" /tr "C:\\Users\\Public\\updater.exe" /sc ONSTART command executed for reboot persistence.',
    indicators: [
      { type: 'Process', value: 'schtasks.exe /create /tn WindowsUpdateTask', reputation: 'Persistence Task Creation' },
    ],
    aiExplanation: 'Unauthorized executable registered in C:\\Users\\Public for startup persistence. Implements MITRE technique [T1053.005 Scheduled Task].',
    remediationSteps: [
      'Delete scheduled task WindowsUpdateTask',
      'Remove binary C:\\Users\\Public\\updater.exe',
    ],
    assignedAnalyst: 'Agent Alex Rivera',
  },
]

export async function fetchThreats(): Promise<ThreatAlert[]> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(mockThreats), 100)
  })
}

export async function updateThreatStatus(
  id: string,
  status: ThreatAlert['status']
): Promise<ThreatAlert> {
  const alert = mockThreats.find((t) => t.id === id)
  if (alert) {
    alert.status = status
    return alert
  }
  throw new Error(`Threat with ID ${id} not found`)
}
